---
name: release

on:
  push:
    branches: [main]

env:
  TEMPLATE_REPOSITORY: telekom-mms/terraform-template

jobs:
  call-readme:
    if: github.repository != '$TEMPLATE_REPOSITORY'
    uses: telekom-mms/.github/.github/workflows/terraform_docs.yml@144dccddbffd39630823571e49a3dbec466828b9 # main
  call-release:
    if: github.repository != '$TEMPLATE_REPOSITORY'
    uses: telekom-mms/.github/.github/workflows/release.yml@144dccddbffd39630823571e49a3dbec466828b9 # main
    secrets:
      GH_BRANCH_PROTECTION_APP_TOKEN: ${{ secrets.GH_BRANCH_PROTECTION_APP_TOKEN }}
    with:
      files: README.md
